Import Debian changes 0.9.0~20160601+git703fedd-3~bpo8+1
xrdp (0.9.0~20160601+git703fedd-3~bpo8+1) jessie-backports; urgency=medium
.
  * Rebuild for jessie-backports.
.
xrdp (0.9.0~20160601+git703fedd-3) unstable; urgency=medium
.
  * Properly handle conffile on upgrade (Closes: #826901)
.
xrdp (0.9.0~20160601+git703fedd-2) unstable; urgency=medium
.
  * Fix build on non-linux platforms (due to systemd dependency).
.
xrdp (0.9.0~20160601+git703fedd-1) unstable; urgency=medium
.
  [ Dominik George, Thorsten Glaser ]
  * New upstream release.
    + Taken from git because there are no recent releases
    + DFSG-free upstream, no more need for Debian patches
    + Working x11rdp backend (native X server access)
    + librfxcodec (better bitmap handling)
    + Better input handling (keymapping, pointer events)
    + xrdp's default backend is now xorgxrdp instead of VNC. This
      makes it get rid of various VNC-related issues and use of VNC
      is discouraged.
      (Closes: #666731, #688083, #685130, #774447, #816098, #469215,
      #780053, #654788, #709595, #709594, #735678, #798643, #469754,
      #741160)
  * Some changes in default config:
    + xorgxrdp is now default
    + Hide files/mountpoints in users' homes using dotfiles and XDG cache dir
  * Add systemd support
  * Full license audit
  * Better integrated X session startup script
  * Change of maintainership (Closes: #719624)
  * Add reportbug note about VNC backend issues
  * Make sure to report on relevant backend packages in reportbug
.
  [ Andreas Tille ]
  * Add myself as Uploader
  * cme fix dpkg-control
  * cme fix dpkg-copyright
  * Refresh quilt patches
  * Build-Depends: libxrandr-dev
  * Fix minor issues in d/rules
  * Fix license of files in common/*
  * Remove unused lintian-overrides
  * Fix section of manpage xrdp-dis.1
  * Fix spelling issue
  * Remove RPATH
.
  [ Mike Gabriel ]
  * debian/copyright:
    + Add auto-genericated template for copyright file.
  * debian/copyright:
    + Various format fixes in Copyright: fields.
    + Place all license texts at EOF.
    + No blanks in short license tags.
    + Add upstream contact's name.
  * debian/control:
    * Add myself to Uploaders: field.
.
  * Upload sponsored and reviewed by Mike Gabriel.
.
xrdp (0.6.1-2) unstable; urgency=medium
.
  [ Johannes Schauer ]
  * Check for libtoolize rather than libtool. Closes: #761793
.
  [ Vincent Bernat ]
  * Upload to unstable.
  * Bump Standards-Version to 3.9.6.
.
xrdp (0.6.1-1) unstable; urgency=low
.
  * New upstream release.
  * Add Norvegian keyboard definition, thanks to Dag-Erling
    Smørgrav. Closes: #709588
  * Use /etc/xrdp/km-default.ini as a fallback for keyboard definition
    before trying `en-US`. Patch from Petter Reinholdtsen. Closes: #709590.
  * Drop session reuse patch which was integrated upstream. Closes: #710007.
  * Update Vcs-* fields.
  * Bump Standards-Version to 3.9.5.
  * Add Lintian overrides for missing manual pages.
.
xrdp (0.6.0-1) unstable; urgency=low
.
  * New upstream version. Closes: #687039.
  * Drop 07-unix-socks-in-var-run.patch: upstream now creates a dedicated
    directory for Unix sockets in /tmp (with mkdtemp).
  * Drop the following patches, applied upstream:
      + alt-gr-fix.patch
      + keycode-fix.patch
  * Bump Standards-Version to 3.9.3.
  * Enable hardening.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -14,17 +14,18 @@ then
   exit 1
 fi
 
-which libtool
+which libtool || which libtoolize
 if ! test $? -eq 0
 then
   echo "error, install libtool"
   exit 1
 fi
 
-touch configure.ac
-touch NEWS
-touch AUTHORS
-touch README
-touch ChangeLog
-ln -s ../config.c $PWD/sesman/tools/config.c
+which pkg-config
+if ! test $? -eq 0
+then
+  echo "error, install pkg-config"
+  exit 1
+fi
+
 autoreconf -fvi
