Import Debian changes 0.10.0~beta1-2
xrdp (0.10.0~beta1-2) experimental; urgency=medium
.
  * d/control: add libcmocka-dev to build-depends.
.
xrdp (0.10.0~beta1-1) experimental; urgency=medium
.
  * New upstream version.

diff --git a/librfxcodec/configure b/librfxcodec/configure
--- a/librfxcodec/configure
+++ b/librfxcodec/configure
@@ -12863,6 +12863,85 @@ fi
 done
 
 
+
+
+
+for flag in -Wmissing-prototypes; do
+  as_CACHEVAR=`printf "%s\n" "ax_cv_check_cflags_-Werror_$flag" | $as_tr_sh`
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether C compiler accepts $flag" >&5
+printf %s "checking whether C compiler accepts $flag... " >&6; }
+if eval test \${$as_CACHEVAR+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+
+  ax_check_save_flags=$CFLAGS
+  CFLAGS="$CFLAGS -Werror $flag"
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main (void)
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"
+then :
+  eval "$as_CACHEVAR=yes"
+else $as_nop
+  eval "$as_CACHEVAR=no"
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+  CFLAGS=$ax_check_save_flags
+fi
+eval ac_res=\$$as_CACHEVAR
+	       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+printf "%s\n" "$ac_res" >&6; }
+if eval test \"x\$"$as_CACHEVAR"\" = x"yes"
+then :
+
+if test ${CFLAGS+y}
+then :
+
+  case " $CFLAGS " in #(
+  *" $flag "*) :
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: : CFLAGS already contains \$flag"; } >&5
+  (: CFLAGS already contains $flag) 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } ;; #(
+  *) :
+
+     as_fn_append CFLAGS " $flag"
+     { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: : CFLAGS=\"\$CFLAGS\""; } >&5
+  (: CFLAGS="$CFLAGS") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }
+     ;;
+esac
+
+else $as_nop
+
+  CFLAGS=$flag
+  { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: : CFLAGS=\"\$CFLAGS\""; } >&5
+  (: CFLAGS="$CFLAGS") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }
+
+fi
+
+else $as_nop
+  :
+fi
+
+done
+
+
 # SIMD is optional
 
 # Check whether --with-simd was given.
@@ -13034,7 +13113,7 @@ printf "%s\n" "$NAFLAGS" >&6; }
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether the assembler ($NASM $NAFLAGS) works" >&5
 printf %s "checking whether the assembler ($NASM $NAFLAGS) works... " >&6; }
 cat > conftest.asm <<EOF
-%line 13037 "configure"
+%line 13116 "configure"
         section .text
         global  _nasmfunc, nasmfunc
 _nasmfunc:
@@ -13259,7 +13338,7 @@ printf "%s\n" "$NAFLAGS" >&6; }
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether the assembler ($NASM $NAFLAGS) works" >&5
 printf %s "checking whether the assembler ($NASM $NAFLAGS) works... " >&6; }
 cat > conftest.asm <<EOF
-%line 13262 "configure"
+%line 13341 "configure"
         section .text
         global  _nasmfunc, nasmfunc
 _nasmfunc:
