update for the new upstream version

diff --git a/debian/xrdp.postinst b/debian/xrdp.postinst
--- a/debian/xrdp.postinst
+++ b/debian/xrdp.postinst
@@ -9,12 +9,12 @@ set -e
 # are no circular dependencies, configured.
 #
 # * old-postinst "abort-upgrade" $new_version
-# * conflictors-postinst "abort-remove" "in-favour" $package
+# * old-postinst "abort-remove"
+# * conflictors-postinst "abort-remove" "in-favour" $new_package
 #	$new_version
-# * postinst "abort-remove"
 # * deconfigureds-postinst "abort-deconfigure" "in-favour"
-#	$failed_install_package $fip_version ["removing"
-#	$conflicting_package $cp_version]
+#	$failed_install_package $fip_version		# new-package
+#	["removing" $conflicting_package $cp_version]	# old-package
 # The package is unpacked; all dependencies are at least Half-Installed,
 # previously been configured, and not removed. In some error situations,
 # dependencies may not be even fully unpacked.
@@ -51,7 +51,6 @@ configure)
 		ln -s /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/xrdp/cert.pem
 		ln -s /etc/ssl/private/ssl-cert-snakeoil.key /etc/xrdp/key.pem
 	)
-
 	;;
 
 abort-upgrade|abort-remove|abort-deconfigure)
@@ -61,7 +60,7 @@ triggered)
 	;;
 
 *)
-	echo >&2 "postinst called with unknown subcommand '$1'"
+	echo >&2 "E: postinst called with unknown subcommand '$1'"
 	exit 1
 	;;
 esac
diff --git a/debian/xrdp.postrm b/debian/xrdp.postrm
--- a/debian/xrdp.postrm
+++ b/debian/xrdp.postrm
@@ -7,17 +7,20 @@ set -e
 # * postrm "remove"
 # * postrm "purge"
 # * old-postrm "upgrade" $new_version
-# * disappearers-postrm "disappear" $overwriter $o_version
+# * disappearers-postrm "disappear" $overwriter_pkg $overwriter_version
 # The package's files have been removed or replaced; only Essential pak-
 # kages may be available; skip gracefully actions requiring Depends.
 #
 # * new-postrm "failed-upgrade" $old_version
+# * new-postrm "failed-upgrade" $old_version $new_version # 1.18.5, stretch
 # Called when 'old-postrm "upgrade"' fails; the new package is unpacked,
 # Essential packages and Pre-Depends are available; the latter have been
 # configured and never removed but may be Unpacked or Half-Configured.
 #
 # * new-postrm "abort-install" [$old_version]
+# * new-postrm "abort-install" [$old_version $new_version] # 1.18.5, stretch
 # * new-postrm "abort-upgrade" $old_version
+# * new-postrm "abort-upgrade" $old_version $new_version # 1.18.5, stretch
 # Called when preinst fails; package is not unpacked. Essential packages
 # and (unpacked or Half-Configured) Pre-Depends are available.
 
@@ -38,7 +41,7 @@ upgrade|disappear|failed-upgrade|abort-install|abort-upgrade)
 	;;
 
 *)
-	echo >&2 "postrm called with unknown subcommand '$1'"
+	echo >&2 "E: postrm called with unknown subcommand '$1'"
 	exit 1
 	;;
 esac
