Remove invalid sudo group check.

diff --git a/debian/xrdp-build-pulse-modules b/debian/xrdp-build-pulse-modules
--- a/debian/xrdp-build-pulse-modules
+++ b/debian/xrdp-build-pulse-modules
@@ -11,10 +11,8 @@
 set -e
 
 if [[ $UID -ne 0 ]] ; then 
-    if ! groups | egrep -q sudo ; then
-        echo "ERROR: You need to be root or a sudo group member."
-        exit 1
-    fi
+	echo "ERROR: You need to be root."
+	exit 1
 fi
 
 TMP=$(mktemp -d)
